name: ci-golang-workflow

on: 
  push:
    branches:
      - develop
  pull_request:
    branches:
      - main
      
jobs:
  
  check-application:
    runs-on: ubuntu-latest
    steps:
      - name: Initial set up
        uses: actions/checkout@v2
      
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      
      - name: Test
        run: go test

      - name: Run
        run: go run math.go

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: felipediasdev/fc2.0-ci-go:latest
