name: ci-golang-workflow

on: 
  pull_request:
    branches:
      - develop
      
jobs:
  
  check-application:
    runs-on: ubuntu-latest
    steps:
      - name: Init set up
        uses: actions/checkout@v2
      
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      
      - name: Test
        run: go test

      - name: Run
        run: go run math.go
