name: ci-golang-workflow

on: [push]

jobs:
  
  check-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      
      - name: Test
        run: go test

      - name: Run
        run: go run math.go
